### ISSUE TITLE
[ADDING STATUS]

### ISSUE THREAD

**Issue by Gameadictive** [renzuzu/renzu_hygiene#7]
I add the hygiene, stress, pee and poo to my hud but know im in the part to set in game i dont know if u understand me.

esx_status? esx_basicneeds? sql?

**Comment by Gameadictive** [comment]
How to integrate?

**Comment by renzuzu** [comment]
you should register the status manualy,
most esx do this on esx_basicneeds

**Comment by Gameadictive** [comment]
Ok i make it work
the thing know is how i make to pee shower poo and that?
I go to a shower or a toilet and is nothing showing.

**Comment by Gameadictive** [comment]
I can´t even wash my hands.

**Comment by Gameadictive** [comment]
I just forgot the dependencies , fixed.
